// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy6BdaY3pr5w5iXSJBnz3Yk3UHu2bPfqM',
    appId: '1:98949199772:web:4935c08661a0a905303a59',
    messagingSenderId: '98949199772',
    projectId: 'kiloism-63680',
    authDomain: 'kiloism-63680.firebaseapp.com',
    databaseURL: 'https://kiloism-63680-default-rtdb.firebaseio.com',
    storageBucket: 'kiloism-63680.appspot.com',
    measurementId: 'G-ZMYRNES7LP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGr0h7YhdxCxlMFE0X2ub5UdHzuPqjsJ8',
    appId: '1:98949199772:android:cf0cd54c4a9b3ca8303a59',
    messagingSenderId: '98949199772',
    projectId: 'kiloism-63680',
    databaseURL: 'https://kiloism-63680-default-rtdb.firebaseio.com',
    storageBucket: 'kiloism-63680.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi_v430psikc3K_0eFlD_31jW3U5HGiTQ',
    appId: '1:98949199772:ios:2b7a5ec11670baae303a59',
    messagingSenderId: '98949199772',
    projectId: 'kiloism-63680',
    databaseURL: 'https://kiloism-63680-default-rtdb.firebaseio.com',
    storageBucket: 'kiloism-63680.appspot.com',
    iosBundleId: 'com.example.kiloiSm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi_v430psikc3K_0eFlD_31jW3U5HGiTQ',
    appId: '1:98949199772:ios:a49d47a9a54ca4cd303a59',
    messagingSenderId: '98949199772',
    projectId: 'kiloism-63680',
    databaseURL: 'https://kiloism-63680-default-rtdb.firebaseio.com',
    storageBucket: 'kiloism-63680.appspot.com',
    iosBundleId: 'com.example.kiloiSm.RunnerTests',
  );
}
